// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentSubjectApplication.DAL;

#nullable disable

namespace StudentSubjectApplication.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20250627090528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentSubject", b =>
                {
                    b.Property<string>("AssignedStudentsid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssignedSubjectsid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AssignedStudentsid", "AssignedSubjectsid");

                    b.HasIndex("AssignedSubjectsid");

                    b.ToTable("StudentSubject");
                });

            modelBuilder.Entity("StudentSubjectApplication.Domain.Entities.Student", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<bool>("assigned")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("dateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentSubjectApplication.Domain.Entities.Subject", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("StudentSubject", b =>
                {
                    b.HasOne("StudentSubjectApplication.Domain.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("AssignedStudentsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentSubjectApplication.Domain.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("AssignedSubjectsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
